### ISSUE TITLE
Add a menu to clear unpined projects from start page

### ISSUE THREAD

**Issue by xiaokangz88** [GrzegorzKozub/ClearRecent#1]
Hi Grzegorz, 

Currently, if I click 'Clear all' from 'Recent Projects and Solutions' menu, it will clear all projects including pinned projects from start page, that is usually not what the user expects.

So, can you add one more menu item to 'Recent Projects and Solutions' menu to clear unpinned projects only.

**Comment by DevX-Cipher** [comment]
I'm looking at this but i don't think its possible the way visual studio shows pinned projects
