### ISSUE TITLE
Fix Update Package PreReqs

### ISSUE THREAD

**Issue by wh0am15533** [GrzegorzKozub/ClearRecent#3]
Error in new package, typo ")" instead of "]". Doesn't properly detect installed core editor.

**Comment by cklenk** [comment]
This does not work on VS 2017 15.9.12. I'm getting microsoft.visualstudio.component.coreeditor missing error when upgrading. I tried uninstalling and reinstalling - same issue. Works no problem on VS 2019 16.1.

Thanks

**Comment by wh0am15533** [comment]
> This does not work on VS 2017 15.9.12. I'm getting microsoft.visualstudio.component.coreeditor missing error when upgrading. I tried uninstalling and reinstalling - same issue. Works no problem on VS 2019 16.1.
> 
> Thanks

cklenk, you need to manually download the package, open it in 7zip and edit the manifest jsons. There were like 3 or 4 different spots I had to edit. Bascially edit the requirements/dependecies. save the file and 7zip will ask if you want to update the archive, say yes, then manually install the package.

**Comment by GrzegorzKozub** [comment]
Visual Studio 2017 compatibility is hopefully fixed now. I published the updated package to the marketplace. If the problem persists, please reopen this issue.
